In [2]:
import os 
import numpy as np
import torch
import pickle
import json

## Numpy

In [34]:
new_audio = np.ones((10, 7))
audio = np.zeros((4, 7))

new_audio[0:2, :] = audio[2:4, :]

print(new_audio)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [35]:
audio_names = ["e ciao", "d ciao", "lofi", "living in new york", "ciaa"]
test = ["ciao", "lofi"]

for name in audio_names:

    if not any(x in name for x in test):
        
        print(name)

living in new york
ciaa


# BOP & MEAN POSE


In [28]:
np_dance = np.ones((5, 50))
np_dance[:, 16] = 0.1
np_dance[:, 17] = 0.3
root = np_dance[:, 2*8:2*9]
np_dance = np_dance - np.tile(root, (1, 25))
np_dance[:, 2*8:2*9] = root

print(np_dance)

[[0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.1 0.3
  0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7
  0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7]
 [0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.1 0.3
  0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7
  0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7]
 [0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.1 0.3
  0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7
  0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7]
 [0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.1 0.3
  0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7
  0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7]
 [0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.1 0.3
  0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7 0.9 0.7
  0.9 0.7 0.9 0.7 0.9 0.

In [27]:
MOTIONS_DIR = "../data/motions/"

beginning_poses = []

for i in os.listdir(MOTIONS_DIR):
    if (i.endswith(".pkl")): 
        motion = np.load(os.path.join(MOTIONS_DIR, i) , allow_pickle=True) 
        l, j, d = motion.shape
        motion = motion.reshape(l, (j*d))
        mean = np.mean(motion, axis=0)
        beginning_poses.append(mean)

mean_array = np.asarray(beginning_poses)

BOS_POSE = np.mean(mean_array, axis=0)

print(str(BOS_POSE).replace(" ", ",").replace(",,", ", "))

[,-3.03933038,197.40993013, -4.02938249, -0.20411807,200.40658281
, -5.71477181, -5.875523, ,200.34909549, -5.77308014, ,3.37541695
,199.4787599, -12.3712766, ,-9.70917155,199.43009712,-12.22367906
, ,9.0159848, 184.74933248,-17.24266724,-15.03735, , 184.82223941
,-18.24799486, 18.45500438,170.64403929,-16.85775607,-23.73141296
,170.69377837,-18.6949286, ,19.15359428,164.08866607, -9.77266799
,-24.92104784,164.24934035,-11.25820301, ,5.22367735,139.70045774
,-21.42948912,-11.29685052,139.79198469,-22.19452003, ,7.53424958
,108.51632543,-14.17712235,-14.2443059, 108.70790672,-15.0563787
, ,7.12587562, 77.89924631,-22.50744766,-13.37533681, 78.14787432
,-23.43227194]


In [11]:
TEST_DIR = "../data/dataset/test/"
print(os.listdir(TEST_DIR))
with open((TEST_DIR + "gBR_sFM_cAll_d05_mBR5_ch12.json")) as f:
    sample = json.loads(f.read())
    music_array = np.array([np.array(x) for x in sample["music"]])
    print(music_array.shape)


['gWA_sBM_cAll_d27_mWA5_ch05.json', 'gJB_sBM_cAll_d08_mJB5_ch07.json', 'gLO_sBM_cAll_d15_mLO5_ch02.json', '.DS_Store', 'gBR_sFM_cAll_d05_mBR5_ch12.json', 'gKR_sBM_cAll_d29_mKR5_ch08.json', 'gJS_sBM_cAll_d03_mJS5_ch03.json', 'gPO_sBM_cAll_d11_mPO5_ch05.json', 'gMH_sBM_cAll_d23_mMH5_ch06.json', 'gHO_sBM_cAll_d21_mHO5_ch08.json', 'gLH_sBM_cAll_d17_mLH5_ch09.json']
(1771, 439)


In [108]:
BOP = np.zeros((54, ))
BOP = np.tile(BOP, (32, 1))

root = np.array([1, 2, 3])

bos = BOP - np.tile(root, (1, 18))

bos[:, 51] = 3
bos[:, 52] = 4
bos[:, 53] = 5

out_frame = torch.from_numpy(bos).float()
out_seq = torch.FloatTensor(32, 1)

print(bos[0])

[-1. -2. -3. -1. -2. -3. -1. -2. -3. -1. -2. -3. -1. -2. -3. -1. -2. -3.
 -1. -2. -3. -1. -2. -3. -1. -2. -3. -1. -2. -3. -1. -2. -3. -1. -2. -3.
 -1. -2. -3. -1. -2. -3. -1. -2. -3. -1. -2. -3. -1. -2. -3.  3.  4.  5.]


In [17]:
pose = np.array([1.65717879e-04, 5.76806666e+01, 1.77991647e+01, 2.83904452e+00
, 6.06789102e+01, 1.61095503e+01,-2.83958684e+00, 6.06217599e+01
, 1.60514467e+01, 6.41940198e+00, 5.97493530e+01, 9.44162840e+00
,-6.67908357e+00, 5.97015183e+01, 9.59322822e+00, 1.20706792e+01
, 4.50052304e+01, 4.56941580e+00,-1.20132797e+01, 4.50802645e+01
, 3.55479801e+00, 2.15286450e+01, 3.08812568e+01, 4.95644498e+00
,-2.07192396e+01, 3.09236114e+01, 3.09857324e+00, 2.22383042e+01
, 2.43203152e+01, 1.20605332e+01,-2.19314823e+01, 2.44590439e+01
, 1.05536155e+01, 8.26935829e+00,-4.73152098e-02, 3.82378866e-01
,-8.26935829e+00, 4.73152098e-02,-3.82378866e-01, 1.05586210e+01
,-3.12299798e+01, 7.62115640e+00,-1.12099623e+01,-3.10378625e+01
, 6.75848723e+00, 1.01434951e+01,-6.18446547e+01,-7.10491983e-01
,-1.03335510e+01,-6.16031763e+01,-1.59934442e+00,-2.96671334e+00
, 1.39761621e+02,-2.17707299e+01])


pose = pose[np.newaxis, :]
pose = pose[np.newaxis, :, :]
pose = pose.reshape(1, 18, 3)



In [20]:


def save_obj(obj, directory, name ):
    with open(directory + name +  '.pkl', 'wb') as f:
        pickle.dump(obj, f, 4)

save_obj(pose, "./", "ciao")

In [4]:
os.listdir("../data/dataset/test/")

['gLH_sBM_cAll_d17_mLH5_ch09_0.json',
 '.DS_Store',
 'gJB_sBM_cAll_d08_mJB5_ch07_0.json',
 'gBR_sFM_cAll_d05_mBR5_ch12_3.json',
 'gLO_sBM_cAll_d15_mLO5_ch02_0.json',
 'gJS_sBM_cAll_d03_mJS5_ch03_0.json',
 'gKR_sBM_cAll_d29_mKR5_ch08_0.json',
 'gBR_sFM_cAll_d05_mBR5_ch12_2.json',
 'gMH_sBM_cAll_d23_mMH5_ch06_0.json',
 'gBR_sFM_cAll_d05_mBR5_ch12_1.json',
 'gBR_sFM_cAll_d05_mBR5_ch12_0.json',
 'gWA_sBM_cAll_d27_mWA5_ch05_0.json',
 'gPO_sBM_cAll_d11_mPO5_ch05_0.json']

In [3]:
ciao = np.load("../../motions/gJS_sFM_cAll_d02_mJS0_ch08.pkl", allow_pickle=True)
print(ciao.shape)

(2878, 18, 3)


## Pytorch

In [3]:
in1 = torch.randn(32, 899, 200)
layer = torch.nn.Linear(200, 512)

output = layer(in1)

print(layer.weight.size())
print(list(layer.parameters())[0].size())
print(list(layer.parameters())[1].size())
print(output.size())

torch.Size([512, 200])
torch.Size([512, 200])
torch.Size([512])
torch.Size([32, 899, 512])


In [48]:
q = torch.randn(256, 899, 64)
k = torch.randn(256, 899, 64)
v = torch.randn(256, 899, 64)
k = k.transpose(1, 2)

attn = torch.bmm(q, k)
print(attn.size())
output = torch.bmm(attn, v)
print(output.size())

output = output.view(8, 32, 899, 64)
print(output.size())
output = output.permute(1, 2, 0, 3).contiguous().view(32, 899, -1)  # b x lq x (n*dv)
print(output.size())

torch.Size([256, 899, 899])
torch.Size([256, 899, 64])
torch.Size([8, 32, 899, 64])
torch.Size([32, 899, 512])


In [30]:
groundtruth_mask = torch.ones(899, 10)
prediction_mask = torch.zeros(899, 10)
mask = torch.cat([prediction_mask, groundtruth_mask], 1).view(-1)[:899] 
print(mask.shape)
print(torch.sum(mask))
# print(mask)

torch.Size([899])
tensor(449.)


In [ ]:
mask = torch.cat([prediction_mask, groundtruth_mask], 1).view(-1)[:899]  # for random
